### ISSUE TITLE
Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by luckeyq** [ozelot379/ConvertMinecraftJavaTextureToBedrockGUI#2]
https://gyazo.com/6abf57ea8b953a8b5aadf32f717e4118

**Comment by ozelot379** [comment]
@luckeyq 
Thanks for your issue report
Can please specify some more details - for instance which texture pack you try to convert?

**Comment by luckeyq** [comment]
https://www.mediafire.com/file/yh1xhh1tsk1buxn/Anime+Memes+V+1.0.0.zip/file

**Comment by luckeyq** [comment]
i did it manually and some textures where broken e.g the beds and i wanted to see if it would work before coverting more texture packs

**Comment by ozelot379** [comment]
Seems that the `pack.mcmeta` json file of the Java texture pack is encoded with an UFT-8 'boom' at the beginning of the file and can therefore not be parsed - I try to fix it with next release

This app already converts the bed textures

**Comment by ozelot379** [comment]
is fixed in v1.4.5
